In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset, drop_first=True, dtype=int)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [8]:
depe=dataset[['classification_yes']]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(indep, depe, test_size=1/3, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
param_grid={'criterion':['gini', 'criterion', 'log_loss'], 'splitter':['best', 'random'], 'max_features':['auto', 'sqrt', 'log2']}
classifier=GridSearchCV(DecisionTreeClassifier(), param_grid, refit=True, verbose=3, cv=5, n_jobs=-1, scoring='f1_weighted')
grid=classifier.fit(X_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
50 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
19 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeClassifier must be a str among {'gini', 'entropy', 'log_loss'}. Got 'criterion' instead.

--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeClassifier must be a str among {'gini', 'log_loss', 'entropy'}. Got 'criterion' instead.

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeClassifier must be a str among {'log_loss', 'entropy', 'gini'}. Got 'criterion' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.95510381 0.96242856 0.95092412 0.95524159
        nan        nan        nan        nan        nan        nan
        nan        nan 0.94740056 0.9734433  0.95463255 0.94764067]
  warnings.warn(

In [20]:

re=grid.cv_results_
grid_prediction=grid.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, grid_prediction)

In [18]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test, grid_prediction)

In [19]:
from sklearn.metrics import f1_score
f1_mac=f1_score(y_test, grid_prediction,average='weighted')
print("The f1_mac value for best parameter {}:".format(grid.best_params_),f1_mac)

The f1_mac value for best parameter {'criterion': 'log_loss', 'max_features': 'sqrt', 'splitter': 'random'}: 0.955283779067923

In [21]:
print("The confusion matrix:\n",cm)

The confusion matrix:
 [[51  0]
 [ 6 76]]

In [22]:
print("The CLF_report:\n",clf_report)

The CLF_report:
               precision    recall  f1-score   support

           0       0.89      1.00      0.94        51
           1       1.00      0.93      0.96        82

    accuracy                           0.95       133
   macro avg       0.95      0.96      0.95       133
weighted avg       0.96      0.95      0.96       133

In [23]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9634146341463414

In [24]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000410,0.000820,0.000000,0.000000,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.001611,0.003222,0.000000,0.000000,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.003831,0.003620,0.014217,0.002954,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.962963,0.981014,0.906705,0.962573,0.962264,0.955104,0.025229,4
3,0.002722,0.002563,0.015711,0.002584,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.963284,0.905069,0.962573,0.981217,1.000000,0.962429,0.031798,2
4,0.003652,0.001885,0.012608,0.002505,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.926567,0.922185,0.962573,0.962264,0.981031,0.950924,0.022759,6
5,0.005934,0.003654,0.011070,0.001068,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.945100,0.943041,0.907035,0.981031,1.000000,0.955242,0.032385,3
6,0.000403,0.000805,0.000000,0.000000,criterion,auto,best,"{'criterion': 'criterion', 'max_features': 'au...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.000409,0.000819,0.000000,0.000000,criterion,auto,random,"{'criterion': 'criterion', 'max_features': 'au...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.000306,0.000612,0.000000,0.000000,criterion,sqrt,best,"{'criterion': 'criterion', 'max_features': 'sq...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
9,0.000403,0.000806,0.000000,0.000000,criterion,sqrt,random,"{'criterion': 'criterion', 'max_features': 'sq...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
10,0.002011,0.003113,0.000000,0.000000,criterion,log2,best,"{'criterion': 'criterion', 'max_features': 'lo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
11,0.001414,0.002353,0.000000,0.000000,criterion,log2,random,"{'criterion': 'criterion', 'max_features': 'lo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
12,0.000607,0.000808,0.000000,0.000000,log_loss,auto,best,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
13,0.002010,0.004019,0.000000,0.000000,log_loss,auto,random,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
14,0.000803,0.001607,0.018219,0.004066,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.981569,0.943041,0.907035,0.962264,0.943093,0.947401,0.024720,8
15,0.002820,0.003951,0.014188,0.004978,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.981569,0.942166,0.981217,0.962264,1.000000,0.973443,0.019672,1
16,0.008064,0.004032,0.012192,0.004015,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",0.944707,0.943699,1.000000,0.922492,0.962264,0.954633,0.025952,5
17,0.004020,0.004923,0.015548,0.004529,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",0.926978,0.924528,0.962573,0.981031,0.943093,0.947641,0.021539,7

In [30]:
age_input=float(input("Age:"))
bp_input=float(input("BP:"))
al_input=float(input("AL:"))
su_input=float(input("SU:"))
bgr_input=float(input("BGR:"))
bu_input=float(input("BU:"))
sc_input=float(input("SC:"))
sod_input=float(input("SOD:"))
pot_input=float(input("POT:"))
hrmo_input=float(input("HRMO:"))
pcv_input=float(input("PCV:"))
wc_input=float(input("WC:"))
rc_input=float(input("RC:"))
sg_b_input=float(input("SG_B:"))
sg_c_input=float(input("SG_C:"))
sg_d_input=float(input("SG_D:"))
sg_e_input=float(input("SG_E:"))
rbc_normal_input=float(input("RBC:"))
pc_normal_input=float(input("PC:"))
pcc_present_input=float(input("PCC:"))
ba_present_input=float(input("BA:"))
htn_yes_input=float(input("HTN:"))
dm_yes_input=float(input("DM:"))
cad_yes_input=float(input("CAD:"))
appet_yes_input=float(input("APPET:"))
pe_yes_input=float(input("PE:"))
ane_yes_input=float(input("ANE:"))

Age: 15
BP: 80
AL: 0.0
SU: 0.0
BGR: 93
BU: 17
SC: 0.9
SOD: 136
POT: 3.9
HRMO: 16.7
PCV: 50
WC: 6200
RC: 5.2
SG_B: 1
SG_C: 0
SG_D: 0
SG_E: 0
RBC: 1
PC: 1
PCC: 0
BA: 0
HTN: 0
DM: 0
CAD: 0
APPET: 1
PE: 0
ANE: 0

In [31]:
CKD_prediction=grid.predict([[age_input, bp_input, al_input, su_input, bgr_input, bu_input, sc_input, sod_input, pot_input, hrmo_input, pcv_input,
       wc_input, rc_input, sg_b_input, sg_c_input, sg_d_input, sg_e_input, rbc_normal_input, pc_normal_input,
       pcc_present_input, ba_present_input, htn_yes_input, dm_yes_input, cad_yes_input,
       appet_yes_input, pe_yes_input, ane_yes_input]])
print("CKD_Prediction{}:".format(CKD_prediction))

CKD_Prediction[1]: