In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset, drop_first=True, dtype=int)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [8]:
depe=dataset[['classification_yes']]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(indep, depe, test_size=1/3, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
param_grid={'n_neighbors':[5,7,10], 'weights':['uniform','distance','None'], 'algorithm':['auto', 'ball_tree', 'kd_tree','brute']}
classifier=GridSearchCV(KNeighborsClassifier(), param_grid, refit=True, verbose=3, cv=5, n_jobs=-1, scoring='f1_weighted')
grid=classifier.fit(X_train, y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
60 fits failed out of a total of 180.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'weights' parameter of KNeighborsClassifier must be a str among {'distance', 'uniform'}, a callable or None. Got 'None' instead.

--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'weights' parameter of KNeighborsClassifier must be a str among {'uniform', 'distance'}, a callable or None. Got 'None' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [0.9590177  0.96273717        nan 0.94447046 0.94447046        nan
 0.92618196 0.94447046        nan 0.9590177  0.96273717        nan
 0.94447046 0.94447046        nan 0.92618196 0.94447046        nan
 0.9590177  0.96273717        nan 0.94447046 0.94447046        nan
 0.92618196 0.94447046        nan 0.9590177  0.96273717        nan
 0.94447046 0.94447046        nan 0.92618196 0.94447046        nan]
  warnings.warn(
C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [12]:
re=grid.cv_results_
grid_prediction=grid.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, grid_prediction)

In [14]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test, grid_prediction)

In [15]:
print("The confusion matrix:\n",cm)

The confusion matrix:
 [[51  0]
 [ 8 74]]

In [16]:
print("The CLF_report:\n",clf_report)

The CLF_report:
               precision    recall  f1-score   support

           0       0.86      1.00      0.93        51
           1       1.00      0.90      0.95        82

    accuracy                           0.94       133
   macro avg       0.93      0.95      0.94       133
weighted avg       0.95      0.94      0.94       133

In [17]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

1.0

In [18]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006979,0.002844,0.443362,0.384581,auto,5,uniform,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.963284,0.962636,0.944023,0.962573,0.962573,0.959018,0.007502,5
1,0.005714,0.001818,0.011702,0.004004,auto,5,distance,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.963284,0.981233,0.944023,0.962573,0.962573,0.962737,0.011770,1
2,0.001096,0.000363,0.000000,0.000000,auto,5,None,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
3,0.005240,0.002575,0.013511,0.001657,auto,7,uniform,"{'algorithm': 'auto', 'n_neighbors': 7, 'weigh...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,9
4,0.003103,0.000902,0.016083,0.002205,auto,7,distance,"{'algorithm': 'auto', 'n_neighbors': 7, 'weigh...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,9
5,0.000465,0.000448,0.000000,0.000000,auto,7,None,"{'algorithm': 'auto', 'n_neighbors': 7, 'weigh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
6,0.006261,0.001350,0.009490,0.002318,auto,10,uniform,"{'algorithm': 'auto', 'n_neighbors': 10, 'weig...",0.854321,0.925764,0.907035,0.981217,0.962573,0.926182,0.044461,21
7,0.004903,0.001380,0.013638,0.002911,auto,10,distance,"{'algorithm': 'auto', 'n_neighbors': 10, 'weig...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,9
8,0.000982,0.000619,0.000000,0.000000,auto,10,None,"{'algorithm': 'auto', 'n_neighbors': 10, 'weig...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
9,0.005770,0.001261,0.018770,0.001715,ball_tree,5,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 5, '...",0.963284,0.962636,0.944023,0.962573,0.962573,0.959018,0.007502,5
10,0.004967,0.000638,0.013942,0.002291,ball_tree,5,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 5, '...",0.963284,0.981233,0.944023,0.962573,0.962573,0.962737,0.011770,1
11,0.000676,0.000560,0.000000,0.000000,ball_tree,5,None,"{'algorithm': 'ball_tree', 'n_neighbors': 5, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
12,0.005367,0.002152,0.015805,0.004543,ball_tree,7,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 7, '...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,9
13,0.005611,0.001791,0.012067,0.001250,ball_tree,7,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 7, '...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,9
14,0.001313,0.001687,0.000000,0.000000,ball_tree,7,None,"{'algorithm': 'ball_tree', 'n_neighbors': 7, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
15,0.003462,0.002556,0.021875,0.002688,ball_tree,10,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 10, ...",0.854321,0.925764,0.907035,0.981217,0.962573,0.926182,0.044461,21
16,0.005063,0.001400,0.014188,0.001199,ball_tree,10,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 10, ...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,9
17,0.000659,0.000549,0.000000,0.000000,ball_tree,10,None,"{'algorithm': 'ball_tree', 'n_neighbors': 10, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
18,0.005568,0.003535,0.018657,0.007325,kd_tree,5,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 5, 'we...",0.963284,0.962636,0.944023,0.962573,0.962573,0.959018,0.007502,5
19,0.005145,0.001298,0.015392,0.003449,kd_tree,5,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 5, 'we...",0.963284,0.981233,0.944023,0.962573,0.962573,0.962737,0.011770,1
20,0.000684,0.000599,0.000000,0.000000,kd_tree,5,None,"{'algorithm': 'kd_tree', 'n_neighbors': 5, 'we...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
21,0.008118,0.003791,0.019257,0.004899,kd_tree,7,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 7, 'we...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,9
22,0.006809,0.002913,0.011708,0.005027,kd_tree,7,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 7, 'we...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,9
23,0.001926,0.002405,0.000000,0.000000,kd_tree,7,None,"{'algorithm': 'kd_tree', 'n_neighbors': 7, 'we...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
24,0.007809,0.003994,0.022482,0.004480,kd_tree,10,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 10, 'w...",0.854321,0.925764,0.907035,0.981217,0.962573,0.926182,0.044461,21
25,0.007015,0.003041,0.013440,0.006727,kd_tree,10,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 10, 'w...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,9
26,0.000507,0.000447,0.000000,0.000000,kd_tree,10,None,"{'algorithm': 'kd_tree', 'n_neighbors': 10, 'w...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
27,0.007698,0.002328,0.015754,0.003465,brute,5,uniform,"{'algorithm': 'brute', 'n_neighbors': 5, 'weig...",0.963284,0.962636,0.944023,0.962573,0.962573,0.959018,0.007502,5
28,0.006876,0.001722,0.014718,0.001889,brute,5,distance,"{'algorithm': 'brute', 'n_neighbors': 5, 'weig...",0.963284,0.981233,0.944023,0.962573,0.962573,0.962737,0.011770,1
29,0.000948,0.000600,0.000000,0.000000,brute,5,None,"{'algorithm': 'brute', 'n_neighbors': 5, 'weig...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
30,0.007098,0.003724,0.015737,0.001653,brute,7,uniform,"{'algorithm': 'brute', 'n_neighbors': 7, 'weig...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,9
31,0.005310,0.000476,0.017915,0.001112,brute,7,distance,"{'algorithm': 'brute', 'n_neighbors': 7, 'weig...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,9
32,0.001068,0.000304,0.000000,0.000000,brute,7,None,"{'algorithm': 'brute', 'n_neighbors': 7, 'weig...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
33,0.006468,0.001486,0.012234,0.001829,brute,10,uniform,"{'algorithm': 'brute', 'n_neighbors': 10, 'wei...",0.854321,0.925764,0.907035,0.981217,0.962573,0.926182,0.044461,21
34,0.005909,0.000920,0.016732,0.001144,brute,10,distance,"{'algorithm': 'brute', 'n_neighbors': 10, 'wei...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,9
35,0.001221,0.000597,0.000000,0.000000,brute,10,None,"{'algorithm': 'brute', 'n_neighbors': 10, 'wei...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25

In [19]:
age_input=float(input("Age:"))
bp_input=float(input("BP:"))
al_input=float(input("AL:"))
su_input=float(input("SU:"))
bgr_input=float(input("BGR:"))
bu_input=float(input("BU:"))
sc_input=float(input("SC:"))
sod_input=float(input("SOD:"))
pot_input=float(input("POT:"))
hrmo_input=float(input("HRMO:"))
pcv_input=float(input("PCV:"))
wc_input=float(input("WC:"))
rc_input=float(input("RC:"))
sg_b_input=float(input("SG_B:"))
sg_c_input=float(input("SG_C:"))
sg_d_input=float(input("SG_D:"))
sg_e_input=float(input("SG_E:"))
rbc_normal_input=float(input("RBC:"))
pc_normal_input=float(input("PC:"))
pcc_present_input=float(input("PCC:"))
ba_present_input=float(input("BA:"))
htn_yes_input=float(input("HTN:"))
dm_yes_input=float(input("DM:"))
cad_yes_input=float(input("CAD:"))
appet_yes_input=float(input("APPET:"))
pe_yes_input=float(input("PE:"))
ane_yes_input=float(input("ANE:"))

Age: 12
BP: 60
AL: 3.0
SU: 0.0
BGR: 148.1126761
BU: 51
SC: 1.8
SOD: 137.528754
POT: 4.62724359
HRMO: 12.1
PCV: 38.86890244
WC: 10300
RC: 4.705597015
SG_B: 0
SG_C: 0
SG_D: 1
SG_E: 0
RBC: 0
PC: 0
PCC: 1
BA: 0
HTN: 0
DM: 0
CAD: 0
APPET: 1
PE: 0
ANE: 0

In [20]:
CKD_prediction=grid.predict([[age_input, bp_input, al_input, su_input, bgr_input, bu_input, sc_input, sod_input, pot_input, hrmo_input, pcv_input,
       wc_input, rc_input, sg_b_input, sg_c_input, sg_d_input, sg_e_input, rbc_normal_input, pc_normal_input,
       pcc_present_input, ba_present_input, htn_yes_input, dm_yes_input, cad_yes_input,
       appet_yes_input, pe_yes_input, ane_yes_input]])
print("CKD_Prediction{}:".format(CKD_prediction))

CKD_Prediction[1]: