In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset, drop_first=True, dtype=int)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [8]:
depe=dataset[['classification_yes']]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(indep, depe, test_size=1/3, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
param_grid={'criterion':['gini', 'entropy', 'log_loss'], 'n_estimators':[10,100,1000], 'max_features':['auto', 'sqrt', 'log2']}
classifier=GridSearchCV(RandomForestClassifier(), param_grid, refit=True, verbose=3, cv=5, n_jobs=-1, scoring='f1_weighted')
grid=classifier.fit(X_train, y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits

C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
45 fits failed out of a total of 135.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan 0.98123739 0.97744358 0.97708904
 0.96621671 0.98480061 0.98480061        nan        nan        nan
 0.98107948 0.97736106 0.98088284 0.9734433  0.97715404 0.97712948
        nan        nan        nan 0.96605811 0.97353957 0.97715404
 0.96598326 0.98088284 0.98088284]
  warnings.warn(
C:\Users\Bagirathan\anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [12]:
re=grid.cv_results_
grid_prediction=grid.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, grid_prediction)

In [14]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test, grid_prediction)

In [15]:
from sklearn.metrics import f1_score
f1_mac=f1_score(y_test, grid_prediction,average='weighted')
print("The f1_mac value for best parameter {}:".format(grid.best_params_),f1_mac)

The f1_mac value for best parameter {'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}: 0.9924946382275899

In [16]:
print("The confusion matrix:\n",cm)

The confusion matrix:
 [[51  0]
 [ 1 81]]

In [17]:
print("The CLF_report:\n",clf_report)

The CLF_report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [18]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

1.0

In [19]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003208,0.003044,0.000000,0.000000,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,19
1,0.002420,0.001709,0.000000,0.000000,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,19
2,0.001430,0.000323,0.000000,0.000000,gini,auto,1000,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,19
3,0.041375,0.002748,0.015579,0.002909,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.981569,0.981014,0.962573,0.981031,1.000000,0.981237,0.011837,3
4,0.360716,0.072872,0.037685,0.013915,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.981569,0.981014,0.962573,0.981031,0.981031,0.977444,0.007438,8
5,4.506998,0.791902,0.185018,0.020970,gini,sqrt,1000,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,0.942166,0.981217,0.981031,0.981031,0.977089,0.018935,13
6,0.074817,0.015221,0.022545,0.006517,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.962264,0.925524,0.981031,0.962264,0.966217,0.024690,16
7,0.720883,0.038716,0.048599,0.006029,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.961755,0.981217,0.981031,1.000000,0.984801,0.014284,1
8,5.810195,0.209439,0.186029,0.006557,gini,log2,1000,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.961755,0.981217,0.981031,1.000000,0.984801,0.014284,1
9,0.001223,0.000756,0.000000,0.000000,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,19
10,0.001942,0.000930,0.000000,0.000000,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,19
11,0.001361,0.000431,0.000000,0.000000,entropy,auto,1000,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,19
12,0.058300,0.005447,0.022720,0.003818,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.981378,0.961755,1.000000,0.962264,1.000000,0.981079,0.016991,4
13,0.578055,0.029714,0.036949,0.004687,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.981569,0.961755,0.981217,0.962264,1.000000,0.977361,0.014259,9
14,5.674064,0.152601,0.201996,0.014294,entropy,sqrt,1000,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.942166,0.981217,0.981031,1.000000,0.980883,0.021119,5
15,0.064683,0.005669,0.022257,0.004285,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.981569,0.942166,0.981217,0.962264,1.000000,0.973443,0.019672,15
16,0.542945,0.021054,0.037134,0.004040,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.942166,0.962573,0.981031,1.000000,0.977154,0.022341,10
17,5.513807,0.112223,0.198241,0.008540,entropy,log2,1000,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.942166,0.981217,0.962264,1.000000,0.977129,0.022389,12
18,0.001063,0.000681,0.000000,0.000000,log_loss,auto,10,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,19
19,0.000814,0.000408,0.000000,0.000000,log_loss,auto,100,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,19
20,0.001146,0.000691,0.000000,0.000000,log_loss,auto,1000,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,19
21,0.059039,0.003122,0.021664,0.001227,log_loss,sqrt,10,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.981569,0.942166,0.925524,0.981031,1.000000,0.966058,0.027679,17
22,0.584398,0.041240,0.036332,0.003726,log_loss,sqrt,100,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.963284,0.942166,0.981217,0.981031,1.000000,0.973540,0.019518,14
23,5.442961,0.143304,0.206596,0.020836,log_loss,sqrt,1000,"{'criterion': 'log_loss', 'max_features': 'sqr...",1.000000,0.942166,0.962573,0.981031,1.000000,0.977154,0.022341,10
24,0.061891,0.005427,0.023903,0.003063,log_loss,log2,10,"{'criterion': 'log_loss', 'max_features': 'log...",0.981569,0.923510,0.962573,0.962264,1.000000,0.965983,0.025415,18
25,0.544931,0.007452,0.046945,0.007676,log_loss,log2,100,"{'criterion': 'log_loss', 'max_features': 'log...",1.000000,0.942166,0.981217,0.981031,1.000000,0.980883,0.021119,5
26,5.418118,0.634376,0.179930,0.037552,log_loss,log2,1000,"{'criterion': 'log_loss', 'max_features': 'log...",1.000000,0.942166,0.981217,0.981031,1.000000,0.980883,0.021119,5

In [20]:
age_input=float(input("Age:"))
bp_input=float(input("BP:"))
al_input=float(input("AL:"))
su_input=float(input("SU:"))
bgr_input=float(input("BGR:"))
bu_input=float(input("BU:"))
sc_input=float(input("SC:"))
sod_input=float(input("SOD:"))
pot_input=float(input("POT:"))
hrmo_input=float(input("HRMO:"))
pcv_input=float(input("PCV:"))
wc_input=float(input("WC:"))
rc_input=float(input("RC:"))
sg_b_input=float(input("SG_B:"))
sg_c_input=float(input("SG_C:"))
sg_d_input=float(input("SG_D:"))
sg_e_input=float(input("SG_E:"))
rbc_normal_input=float(input("RBC:"))
pc_normal_input=float(input("PC:"))
pcc_present_input=float(input("PCC:"))
ba_present_input=float(input("BA:"))
htn_yes_input=float(input("HTN:"))
dm_yes_input=float(input("DM:"))
cad_yes_input=float(input("CAD:"))
appet_yes_input=float(input("APPET:"))
pe_yes_input=float(input("PE:"))
ane_yes_input=float(input("ANE:"))

Age: 15
BP: 60
AL: 3.0
SU: 0.0
BGR: 86
BU: 15
SC: 0.6
SOD: 138
POT: 4
HRMO: 11
PCV: 33
WC: 7700
RC: 3.8
SG_B: 0
SG_C: 0
SG_D: 0
SG_E: 0
RBC: 1
PC: 1
PCC: 0
BA: 0
HTN: 1
DM: 1
CAD: 0
APPET: 1
PE: 0
ANE: 0

In [21]:
CKD_prediction=grid.predict([[age_input, bp_input, al_input, su_input, bgr_input, bu_input, sc_input, sod_input, pot_input, hrmo_input, pcv_input,
       wc_input, rc_input, sg_b_input, sg_c_input, sg_d_input, sg_e_input, rbc_normal_input, pc_normal_input,
       pcc_present_input, ba_present_input, htn_yes_input, dm_yes_input, cad_yes_input,
       appet_yes_input, pe_yes_input, ane_yes_input]])
print("CKD_Prediction{}:".format(CKD_prediction))

CKD_Prediction[1]: